### ISSUE TITLE
In Grade Centre all of the top Banner and Navigation is lost under new version

### ISSUE THREAD

**Issue by jthambly** [timklapdor/learning-materials#140]
Testing the new version, In Grade Centre, the top Banner/navigation is lost.

Outside of Grade Centre:

![image](https://user-images.githubusercontent.com/33741581/48686123-77e51800-ec0e-11e8-8c91-96fe3c6b0868.png)

In Grade Centre:

![image](https://user-images.githubusercontent.com/33741581/48686130-7fa4bc80-ec0e-11e8-8b2b-bd5049f25784.png)

Unsure if this is a theme issue, or Blackboard issue, logging with both. If a Bb issue, I will close this issue.

**Comment by jthambly** [comment]
In QA

**Comment by jthambly** [comment]
Blackboard indicated that this is not a Blackboard issue, but an issue with the theme customisation.

**Comment by jthambly** [comment]
This issue does not seem to be occurring under devel - unsure if a fix is in progress?

**Comment by jthambly** [comment]
Under further review, **this issue still is present** in Devel - under normal grade centre view. If Grade Centre is locked or has a notification/status bar, then it will show correctly.

**Comment by jthambly** [comment]
Might be an opacity setting set as 0, instead of 1.

![image](https://user-images.githubusercontent.com/33741581/49704108-e728b780-fc62-11e8-8c1d-9a4bdbd24801.png)

**Comment by jsloane** [comment]
Looks like this issue is caused by CSS being pulled in from this file: https://interact2qa.csu.edu.au/webapps/spreview/css/preview-on.css?v=3500.0.1-rel.59+219b762

.global-nav-bar-wrap {
    display: none;
}
#globalNavPageNavArea {
    opacity: 0;
    filter: alpha(opacity=0);
}

The comment from the CSS file indicates that it should only be used when Student Preview mode is being used. If we override these styles, it may break the Student Preview. This looks like a Blackboard bug that should be logged with Blackboard.

**Comment by jthambly** [comment]
The updated theme has fixed the issue.
